# Generated by Django 2.2 on 2020-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitron',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='bitron',
            name='modified',
        ),
        migrations.AddField(
            model_name='bitron',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
        ),
    ]
