# Generated by Django 2.2 on 2020-04-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_bot', '0003_remove_bitron_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitron',
            options={},
        ),
    ]
